import os
import streamlit as st
import joblib
from utils.ui import apply_ui

# --- DYNAMIC CONFIGURATION ---
# Get the absolute path to the project root
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
METRICS_PATH = os.path.join(BASE_DIR, "model", "metrics.pkl")

# Page Config
st.set_page_config(page_title="About Project | Smart City", page_icon="ℹ️", layout="wide")
apply_ui()

# Header Section
st.markdown('<div class="badge">Project Documentation</div>', unsafe_allow_html=True)
st.title("ℹ️ About the Smart City AI Project")
st.markdown('<p class="subtle-text">MSc Dissertation: Traffic Hotspot Prediction & Urban Decision Support System</p>', unsafe_allow_html=True)

# 1. Project Overview & Mission
col_a, col_b = st.columns([2, 1])

with col_a:
    st.markdown("""
    <div style="background-color: #f8f9fa; padding: 20px; border-radius: 10px; border-left: 5px solid #0f6cbd;">
        <h3 style="margin-top:0;">Project Mission</h3>
        <p>This platform provides urban planners and citizens with data-driven insights into traffic 
        congestion patterns. By integrating <b>Supervised Learning (Random Forest)</b> and 
        <b>Unsupervised Spatial Clustering (DBSCAN)</b>, the system identifies high-density 
        risk 'hotspots' and simulates actionable interventions to improve city mobility.</p>
    </div>
    """, unsafe_allow_html=True)

with col_b:
    st.subheader("🛠️ Technical Stack")
    st.info("**Frontend:** Streamlit Framework")
    st.success("**ML Engine:** Scikit-Learn (RF & DBSCAN)")
    st.warning("**Geo-Spatial:** Folium & OpenStreetMap")
    st.error("**Reporting:** ReportLab (PDF Engine)")

# 2. Performance Metrics Section (The "Science" of the Project)
st.divider()
st.subheader("📊 Model Evaluation & Performance")

if os.path.exists(METRICS_PATH):
    try:
        # Load metrics generated by train_model.py
        metrics = joblib.load(METRICS_PATH)
        
        # Professional Metric Grid
        m1, m2, m3, m4 = st.columns(4)
        m1.metric("Model Accuracy", f"{metrics.get('accuracy', 0)*100:.2f}%")
        m2.metric("Weighted Precision", f"{metrics.get('precision_weighted', 0):.4f}")
        m3.metric("Weighted Recall", f"{metrics.get('recall_weighted', 0):.4f}")
        m4.metric("F1 Score", f"{metrics.get('f1_weighted', 0):.4f}")
        
        with st.expander("📄 View Detailed Classification Report (Matrix)"):
            st.write("This report details how well the model predicts 'Hotspot' vs 'Normal' traffic.")
            report = metrics.get("classification_report", "No report available.")
            st.code(report, language="text")
            
    except Exception as e:
        st.error(f"Error loading model metrics: {e}")
else:
    st.warning("⚠️ Metrics File Not Found. Please ensure you have run the 'train_model.py' script locally or in the cloud environment to generate 'model/metrics.pkl'.")

# 3. Architecture & Methodology
st.divider()
st.subheader("🏗️ System Architecture")

# Using a flow-chart style representation
c1, c2, c3 = st.columns(3)

with c1:
    st.markdown("#### 📥 Data Ingestion")
    st.write("- Historical Traffic CSV")
    st.write("- Spatial Coordinates (Mumbai)")
    st.write("- Weather & Event Flags")

with c2:
    st.markdown("#### ⚙️ Processing Layer")
    st.write("- **DBSCAN:** Density Clustering")
    st.write("- **Random Forest:** Probability")
    st.write("- **Isolation Forest:** Anomaly")

with c3:
    st.markdown("#### 📤 Output Layer")
    st.write("- Interactive Folium Maps")
    st.write("- PDF Technical Reports")
    st.write("- Intervention Advisories")

# 4. Future Scope
st.divider()
st.subheader("🚀 Future Roadmap")
roadmap_col1, roadmap_col2 = st.columns(2)

with roadmap_col1:
    st.markdown("""
    1. **Real-time API Integration:** Fetching live data from Google Maps or TomTom Traffic APIs.
    2. **Time-Series Forecasting:** Implementing LSTMs (Long Short-Term Memory) for temporal prediction.
    """)

with roadmap_col2:
    st.markdown("""
    3. **Dynamic Routing:** Integrating Dijkstra’s algorithm to suggest routes that actively bypass hotspots.
    4. **Mobile Alerts:** Developing a Twilio-based SMS alert system for emergency service vehicles.
    """)

# Footer
st.markdown("---")
st.caption("© 2026 Smart City AI System | MSc Dissertation Project | Mumbai, Maharashtra, India")
