import os
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors

# --- DYNAMIC PATHING ---
# Ensures the output directory is relative to the project root
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_OUTPUT_DIR = os.path.join(BASE_DIR, "output_reports")

def generate_prediction_report(filename, report_data):
    """
    Generates a PDF report safely for production.
    - Handles directory creation automatically.
    - Strips non-renderable characters to prevent PDF engine crashes.
    """
    # 1. Ensure the directory exists
    if not os.path.exists(DEFAULT_OUTPUT_DIR):
        os.makedirs(DEFAULT_OUTPUT_DIR, exist_ok=True)
    
    # Define the full absolute path for the file
    output_path = os.path.join(DEFAULT_OUTPUT_DIR, filename)

    try:
        # 2. Initialize Canvas
        c = canvas.Canvas(output_path, pagesize=A4)
        width, height = A4
        
        # Style Configuration
        font_name = "Helvetica"
        bold_font = "Helvetica-Bold"
        margin = 60
        line_height = 25
        y = height - 80

        # 3. Header Styling
        c.setFont(bold_font, 20)
        c.setFillColor(colors.HexColor("#0F6CBD")) # Smart City Blue
        c.drawString(margin, y, "Smart City Traffic Prediction Report")
        
        y -= 15
        c.setStrokeColor(colors.lightgrey)
        c.setLineWidth(1)
        c.line(margin, y, width - margin, y) # Visual Separator
        y -= 40

        # 4. Content Logic
        c.setFillColor(colors.black)
        
        for key, value in report_data.items():
            # SANITIZATION: ReportLab's standard fonts cannot handle emojis or special symbols.
            # We strip them to avoid 'Character not found' errors on the cloud.
            safe_key = str(key).replace(":", "").strip()
            # Remove non-ASCII characters and emojis
            safe_value = str(value).encode('ascii', 'ignore').decode('ascii').strip()
            
            # Label (Bold)
            c.setFont(bold_font, 12)
            c.drawString(margin, y, f"{safe_key}:")
            
            # Value (Regular) - Shifted right by 150 units
            c.setFont(font_name, 11)
            c.drawString(margin + 150, y, safe_value)
            
            y -= line_height
            
            # 5. Page Overflow Handling (New Page if near bottom)
            if y < margin + 60:
                c.showPage()
                y = height - margin
                c.setFont(font_name, 11)

        # 6. Footer (Page Numbers or Project Tag)
        c.setFont("Helvetica-Oblique", 9)
        c.setFillColor(colors.grey)
        c.line(margin, 50, width - margin, 50)
        c.drawString(margin, 35, "Generated by Mumbai Smart City Framework - MSc Dissertation © 2026")

        c.save()
        return output_path

    except Exception as e:
        # Log to the Streamlit app logs if on the cloud
        import streamlit as st
        st.error(f"Failed to generate PDF: {e}")
        return None
