import os
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader

def generate_prediction_report(output_path, report_data):
    """
    Generates a PDF report safely. 
    Includes directory checks and character sanitization to prevent Streamlit crashes.
    """
    try:
        # 1. Ensure the directory exists
        output_dir = os.path.dirname(output_path)
        if output_dir and not os.path.exists(output_dir):
            os.makedirs(output_dir, exist_ok=True)

        # 2. Initialize Canvas
        c = canvas.Canvas(output_path, pagesize=A4)
        width, height = A4
        
        # Configuration
        font_name = "Helvetica"
        bold_font = "Helvetica-Bold"
        margin = 50
        line_height = 20
        y = height - 60

        # 3. Header Styling
        c.setFont(bold_font, 18)
        c.setStrokeColorRGB(0.06, 0.42, 0.74) # Smart City Blue
        c.drawString(margin, y, "Smart City Traffic Prediction Report")
        
        y -= 10
        c.line(margin, y, width - margin, y) # Separator line
        y -= 30

        # 4. Content Logic
        c.setFont(font_name, 11)
        
        for key, value in report_data.items():
            # Sanitize input: Remove characters that Helvetica cannot render (like emojis)
            # and ensure the value is a string
            safe_key = str(key).replace(":", "")
            safe_value = str(value).encode('ascii', 'ignore').decode('ascii')
            
            line = f"{safe_key}: {safe_value}"
            
            # Draw Label in Bold, Value in Regular
            c.setFont(bold_font, 11)
            c.drawString(margin, y, f"{safe_key}:")
            c.setFont(font_name, 11)
            c.drawString(margin + 120, y, safe_value)
            
            y -= line_height
            
            # 5. Page Overflow Handling
            if y < margin + 40:
                c.showPage()
                y = height - margin
                c.setFont(font_name, 11) # Re-apply font for new page

        # 6. Footer
        c.setFont("Helvetica-Oblique", 8)
        c.setStrokeColorRGB(0.7, 0.7, 0.7)
        c.drawString(margin, 30, "Generated by Smart City AI System - MSc Project 2026")

        c.save()
        return output_path

    except Exception as e:
        # We catch the error but don't crash the whole app
        print(f"PDF Generation Error: {e}")
        return None